version: '3.8'
services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
    - mode: ingress
      protocol: tcp
      published: 16686
      target: 16686
    - mode: ingress
      protocol: udp
      published: 6831
      target: 6831
    - mode: ingress
      protocol: udp
      published: 6832
      target: 6832
    - mode: ingress
      protocol: tcp
      published: 5778
      target: 5778
    - mode: ingress
      protocol: tcp
      published: 14268
      target: 14268
  first:
    build: .
    ports:
    - 5000:3000
    environment:
    - "SERVICE_NAME=first-app"
    - "TARGET_HOST=second"
    - "TARGET_PATH=request"
    - "OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger"
    depends_on:
    - jaeger
  second:
    build: .
    ports:
    - 5001:3000
    environment:
    - "SERVICE_NAME=second-app"
    - "TARGET_HOST=third"
    - "TARGET_PATH=error"
    - "OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger"
    depends_on:
    - jaeger
  third:
    build: .
    ports:
    - 5002:3000
    environment:
    - "SERVICE_NAME=third-app"
    - "OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger"
    depends_on:
    - jaeger